PIZZA_TOPPINGS = {
    "sauces": ["Tomato", "BBQ", "White", "Pesto"],
    "cheese": [
        "Mozzarella",
        "Parmesan",
        "Provolone",
        "Ricotta",
        "Bleu",
        "Goat",
        "Feta",
        "Buratta",
        "Gorgonzola",
        "Gruyère",
        "Fontina",
        "Pepper jack",
        "Cheddar",
        "Brie",
        "Colby Jack",
        "Pecorino Romano",
    ],
    "topping_1": [
        "Pepperoni",
        "Sausage",
        "Meatball",
        "Ham",
        "Bacon",
        "Pork",
        "Chorizo",
        "Chicken",
        "Anchovies",
        "Pineapple",
        "Salami",
        "Extra cheese",
    ],
    "topping_2": [
        "Green peppers",
        "Red peppers",
        "Orange peppers",
        "Banana peppers",
        "Mushrooms",
        "Sweet onions",
        "Red onions",
        "Spring onions",
        "Caramelized onions",
        "Red onion",
        "Jalapeño peppers",
        "Spinach",
        "Cherry tomatoes",
        "Sweetcorn",
        "Olives",
        "Basil",
    ],
}
